services:
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORT=8080
    restart: unless-stopped
    user: $APP_UID
    working_dir: /app
    volumes:
      - ./data:/app/data